Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-10, with the labels that each got.

#728 Copy authors file into "src/bin/hamcore" automatically
  .gitignore
  CMakeLists.txt
  src/BuildAll.cmd
  src/bin/hamcore/authors.txt
Labels: build & release

#733 Mayaqua/OS: improve UnixGetOsInfo() so that it retrieves info on recent Linux/BSD systems
  src/Cedar/Proto_OpenVPN.c
  src/Cedar/Proto_OpenVPN.h
  src/Mayaqua/Memory.c
  src/Mayaqua/Memory.h
  src/Mayaqua/Str.c
  src/Mayaqua/Str.h
  src/Mayaqua/Unix.c
Labels: os/BSD, os/Linux

#741 Added OpenSSL and zlib .pdb files for .lib for Windows.
  src/BuildAll.cmd
  src/BuildFiles/Library/vs2008/Win32_Debug/ossl_static.pdb
  src/BuildFiles/Library/vs2008/Win32_Debug/vc90.pdb
  src/BuildFiles/Library/vs2008/Win32_Release/ossl_static.pdb
  src/BuildFiles/Library/vs2008/x64_Debug/ossl_static.pdb
  src/BuildFiles/Library/vs2008/x64_Debug/vc90.pdb
  src/BuildFiles/Library/vs2008/x64_Release/ossl_static.pdb
  src/BuildFiles/Library/vs2017/Win32_Debug/ossl_static.pdb
  src/BuildFiles/Library/vs2017/Win32_Debug/vc90.pdb
  src/BuildFiles/Library/vs2017/Win32_Release/ossl_static.pdb
  src/BuildFiles/Library/vs2017/x64_Debug/ossl_static.pdb
  src/BuildFiles/Library/vs2017/x64_Debug/vc90.pdb
  src/BuildFiles/Library/vs2017/x64_Release/ossl_static.pdb
Labels: build & release, os/Windows

#744 gitlab-ci: enable ubuntu 12.04 builds
  .gitlab-ci.yml
  CMakeLists.txt
  src/Mayaqua/CMakeLists.txt
  src/Mayaqua/Encrypt.c
Labels: build & release, os/Linux

#749 MayaType.h: fix pointer casting warnings
  src/Mayaqua/MayaType.h
Labels: cleanup

#750 Memory.c: fix pointer cast in TrackChangeObjSize() call
  src/Mayaqua/Memory.c
Labels: cleanup

#757 CMake: build all targets in the same directory, so that "hamcore.se2" doesn't have to be copied for each of them
  .travis.yml
  src/CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpncmd/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
  src/vpntest/CMakeLists.txt
Labels: build & release

#761 CMake: build Cedar and Mayaqua as shared libraries, create "common" package
  CMakeLists.txt
  src/Cedar/CMakeLists.txt
  src/Mayaqua/CMakeLists.txt
Labels: build & release

#764 adjust systemd paths according to installation path
  .appveyor.yml
  .gitlab-ci.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
  systemd/softether-vpnbridge.service
  systemd/softether-vpnclient.service
  systemd/softether-vpnserver.service
Labels: build & release

#767 CMake: add dynamic libraries to RPATH
  .appveyor.yml
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build & release

#770 CMake: change ${CMAKE_SOURCE_DIR}/tmp with ${CMAKE_BINARY_DIR}
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
Labels: build & release

#773 ci repair and refactoring
  .appveyor.yml
  .ci/appveyor_afterbuild.sh
  .gitlab-ci.yml
Labels: build & release

#776 AppVeyor: non interactive mode of journalctl
  .appveyor.yml
Labels: build & release

#782 AppVeyor: run "vpntest" for ubuntu 18.04
  .appveyor.yml
  .ci/memory-leak-test.sh
Labels: build & release

#785 README.md: add gitlab-ci badge
  README.md
Labels: documentation

#789 gitlab-ci: add "vpntest" memory tests
  .gitlab-ci.yml
Labels: build & release

#795 docs(BUILD_UNIX): add macOS specifics
  src/BUILD_UNIX.md
Labels: build & release

#794 Proto_OpenVPN.c: move encrypt and decrypt process into dedicated functions
  src/Cedar/Proto_OpenVPN.c
Labels: cleanup, protocol/OpenVPN
