Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-09, with the labels that each got.

#684 src/Mayaqua/Kernel: remove unused variable, functions
  src/Mayaqua/Kernel.c
  src/Mayaqua/Kernel.h
Labels: cleanup

#685 src/Cedar/BridgeUnix.c: resolve possible null pointer dereference
  src/Cedar/BridgeUnix.c
Labels: cleanup

#686 src/Cedar/Server: resolve possible null reference exception, remove unused functions, variable, duplicate assignment and conditional
  src/Cedar/Server.c
  src/Cedar/Server.h
Labels: cleanup

#691 Cedar: replace "Interop_" and "IPsec_" with "Proto_" in the protocol-specific source/header files' names
  src/Cedar/Cedar.h
  src/Cedar/Cedar.vcproj
  src/Cedar/IPC.c
  src/Cedar/IPC.h
  src/Cedar/Proto_EtherIP.c
  src/Cedar/Proto_EtherIP.h
  src/Cedar/Proto_IKE.c
  src/Cedar/Proto_IKE.h
  src/Cedar/Proto_IPsec.c
  src/Cedar/Proto_IPsec.h
  src/Cedar/Proto_IkePacket.c
  src/Cedar/Proto_IkePacket.h
  src/Cedar/Proto_L2TP.c
  src/Cedar/Proto_L2TP.h
  src/Cedar/Proto_OpenVPN.c
  src/Cedar/Proto_OpenVPN.h
  src/Cedar/Proto_PPP.c
  src/Cedar/Proto_PPP.h
  src/Cedar/Proto_SSTP.c
  src/Cedar/Proto_SSTP.h
  src/Cedar/Proto_Win7.c
  src/Cedar/Proto_Win7.h
  src/Cedar/Proto_Win7Inner.h
Labels: cleanup

#690 CMake: install systemd configuration files
  .travis.yml
  src/CMakeLists.txt
  systemd/softether-vpnbridge.service
  systemd/softether-vpnclient.service
  systemd/softether-vpnserver.service
Labels: build & release, os/Linux

#694 Proto_IkePacket.c: fix MD5, SHA-256, SHA-384 and SHA-512 implementation
  src/Cedar/Proto_IkePacket.c
Labels: protocol/L2TP

#698 Clean up Solaris device name parsing code to eliminate Coverity errors
  src/Cedar/BridgeUnix.c
Labels: cleanup, os/Solaris

#699 src/Cedar/Hub: resolve potential null pointer dereference, remove unused functions
  src/Cedar/Hub.c
  src/Cedar/Hub.h
Labels: cleanup

#701 src/Cedar/Radius: resolve several coverity "issues"
  src/Cedar/Radius.c
Labels: cleanup

#705 src/Cedar/Client.c: remove not needed condition
  src/Cedar/Client.c
Labels: cleanup

#706 BridgeUnix.c: add TAP local bridge support for FreeBSD
  src/Cedar/BridgeUnix.c
Labels: os/BSD

#695 Revamp digest functions
  src/Cedar/Account.c
  src/Cedar/Admin.c
  src/Cedar/Bridge.c
  src/Cedar/BridgeWin32.c
  src/Cedar/CM.c
  src/Cedar/Client.c
  src/Cedar/Command.c
  src/Cedar/Connection.c
  src/Cedar/DDNS.c
  src/Cedar/EM.c
  src/Cedar/EtherLog.c
  src/Cedar/Hub.c
  src/Cedar/IPC.c
  src/Cedar/Layer3.c
  src/Cedar/NM.c
  src/Cedar/Nat.c
  src/Cedar/NativeStack.c
  src/Cedar/NullLan.c
  src/Cedar/Proto_IKE.c
  src/Cedar/Proto_IkePacket.c
  src/Cedar/Proto_PPP.c
  src/Cedar/Protocol.c
  src/Cedar/Radius.c
  src/Cedar/SM.c
  src/Cedar/Sam.c
  src/Cedar/Server.c
  src/Cedar/Session.c
  src/Cedar/UdpAccel.c
  src/Cedar/Virtual.c
  src/Cedar/WebUI.c
  src/Cedar/WinUi.c
  src/Cedar/Wpc.c
  src/Mayaqua/Cfg.c
  src/Mayaqua/Encrypt.c
  src/Mayaqua/Encrypt.h
  src/Mayaqua/Kernel.c
  src/Mayaqua/Memory.c
  src/Mayaqua/Microsoft.c
  src/Mayaqua/Network.c
  src/Mayaqua/Table.c
  src/Mayaqua/Unix.c
Labels: cleanup

#713 AppVeyor: add Ubuntu 16.04 and 18.04 builds
  .appveyor.yml
Labels: build & release, os/Linux

#715 src/Cedar: resolve possible null pointer dereference and silence dead code warning
  src/Cedar/Client.c
  src/Cedar/Hub.c
Labels: cleanup

#717 Added some output/obj folders to git ignore.
  .gitignore
Labels: build & release

#722 cmake: compare PROJECT_VERSION against src/CurrentBuild.txt
  CMakeLists.txt
Labels: build & release

#725 BridgeUnix.c: enable local bridge function on all BSD systems
  src/Cedar/BridgeUnix.c
Labels: os/BSD

#718 src/Cedar/BridgeUnix.c: resolve null pointer dereference
  src/Cedar/BridgeUnix.c
  src/Mayaqua/Object.c
Labels: cleanup
