Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-12, with the labels that each got.

#830 CI: avoid not needed builds, make AppVeyor upload src with submodules
  .appveyor.yml
  .gitlab-ci.yml
Labels: build & release

#828 Added the "OpenVPNPushDummyIPv4AddressOnL2Mode" option for the OpenVPN L2 mode.
  src/Cedar/Cedar.c
  src/Cedar/Cedar.h
  src/Cedar/Proto_OpenVPN.c
  src/Cedar/Server.c
Labels: protocol/OpenVPN

#834 setup azure pipelines
  .appveyor.yml
  .gitlab-ci.yml
  azure-pipelines.yml
  configure
Labels: build & release

#838 cleanup: remove ChangeLog, it is not actively maintained
  ChangeLog
Labels: cleanup

#845 Cedar/IPC.c: fix memory leak occurring when both the username and common name are not present (OpenVPN)
  src/Cedar/IPC.c
  src/Cedar/Protocol.c
Labels: protocol/OpenVPN

#850 travis-ci: try to fix coverity scan
  .travis.yml
Labels: build & release
