Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-11, with the labels that each got.

#797 AppVeyor: enable parallel builds and push systemctl log as artifact
  .appveyor.yml
  .ci/appveyor_afterbuild.sh
Labels: build & release

#798 src/Cedar/Proto_IkePacket: remove unused functions, redundant assignment
  src/Cedar/Proto_IkePacket.c
  src/Cedar/Proto_IkePacket.h
Labels: cleanup

#796 Cedar/Proto_OpenVPN: add support for GCM ciphers
  src/Cedar/Proto_OpenVPN.c
  src/Cedar/Proto_OpenVPN.h
  src/Mayaqua/Encrypt.c
  src/Mayaqua/Encrypt.h
  src/bin/hamcore/openvpn_sample.ovpn
Labels: protocol/OpenVPN

#793 Added Windows CMake setup info
  src/BUILD_WINDOWS.md
Labels: build & release

#790 Add support for SOCKS5 proxy protocol
  src/Cedar/CM.c
  src/Cedar/Cedar.h
  src/Cedar/Command.c
  src/Cedar/Command.h
  src/Cedar/Protocol.c
  src/Cedar/Protocol.h
  src/Cedar/SM.c
  src/Cedar/Wpc.c
  src/PenCore/PenCore.rc
  src/PenCore/resource.h
  src/bin/hamcore/strtable_cn.stb
  src/bin/hamcore/strtable_en.stb
  src/bin/hamcore/strtable_ja.stb
  src/bin/hamcore/strtable_ko.stb
  src/bin/hamcore/strtable_ru.stb
  src/bin/hamcore/strtable_tw.stb
Labels: feature

#802 src: change "afxres.h" to "winres.h" in all resource files, to remove MFC dependency
  src/BUILD_WINDOWS.md
  src/Neo/Neo.rc
  src/Neo6/Neo6.rc
  src/PenCore/PenCore.rc
  src/See/See.rc
  src/SeeDll/SeeDll.rc
  src/Wfp/Wfp.rc
  src/vpn16/Vpn16.rc
  src/vpnbridge/vpnbridge.rc
  src/vpnclient/vpnclient.rc
  src/vpncmd/vpncmd.rc
  src/vpncmdsys/vpncmdsys.rc
  src/vpncmgr/vpncmgr.rc
  src/vpndrvinst/vpndrvinst.rc
  src/vpninstall/vpninstall.rc
  src/vpnserver/vpnserver.rc
  src/vpnsetup/vpnsetup.rc
  src/vpnsmgr/vpnsmgr.rc
  src/vpntest/vpntest.rc
Labels: build & release

#806 src/Cedar/Protocol, src/Cedar/Session: cleanup, remove unused functions, variables
  src/Cedar/Protocol.c
  src/Cedar/Protocol.h
  src/Cedar/Session.h
Labels: cleanup

#805 travis-ci: add libressl build, make builds parallel, remove not needed brew
  .ci/build-libressl.sh
  .ci/build-openssl.sh
  .travis.yml
Labels: build & release

#807 gitlab-ci: enable SAST
  .gitlab-ci.yml
Labels: build & release

#812 Cedar/Proto_OpenVPN.c: don't release data channel if it's not established, improve logic and debug messages
  src/Cedar/Proto_OpenVPN.c
Labels: protocol/OpenVPN

#814 travis-ci: run Coverity only after openssl is built
  .travis.yml
Labels: build & release

#817 AppVeyor: renew github token, renamed APPVEYOR_REPO_TAG to upper case,
  .appveyor.yml
  .ci/appveyor-vpntest.ps1
Labels: build & release

#816 Cedar: add new "UsernameHubSeparator" configuration option for the server, to specify a different character from '@'
  src/Cedar/Cedar.h
  src/Cedar/Proto_PPP.c
  src/Cedar/Server.c
Labels: feature

#818 src/Mayaqua/Cfg: remove unused functions, variables
  src/Mayaqua/Cfg.c
  src/Mayaqua/Cfg.h
Labels: cleanup

#819 CMake: build targets with versioning info on Windows
  CMakeLists.txt
  src/BuildFiles/VerScript/ver.rc
  src/BuildUtil/Win32BuildUtil.cs
  src/CMakeLists.txt
  src/Cedar/CMakeLists.txt
  src/Mayaqua/CMakeLists.txt
  src/PenCore/CMakeLists.txt
  src/hamcorebuilder/CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpncmd/CMakeLists.txt
  src/vpncmgr/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
  src/vpnsmgr/CMakeLists.txt
  src/vpntest/CMakeLists.txt
Labels: build & release, os/Windows

#820 travis-ci: do not do anything on tag, source is packed automatically
  .travis.yml
Labels: build & release, cleanup

#821 AppVeyor refactor
  .appveyor.yml
  .ci/appveyor-deb-install-test.sh
Labels: build & release

#824 AppVeyor: shorten artifacts path, move github token to variables
  .appveyor.yml
Labels: build & release

#825 src/Mayaqua/Mayaqua: remove unused functions
  src/Mayaqua/Mayaqua.c
  src/Mayaqua/Mayaqua.h
Labels: cleanup

#826 missing warning_ru.txt which caused null pointer dereference
  src/BuildUtil/BuildUtilCommands.cs
  src/BuildUtil/UnixBuildSoftwares.cs
  src/bin/hamcore/warning_ru.txt
Labels: bug
