Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-08, with the labels that each got.

#598 Travis CI: upgrade everything on MacOS
  .travis.yml
Labels: build & release

#599 Travis CI: cache Homebrew downloads
  .travis.yml
Labels: build & release

#600 Interop_OpenVPN: remove lists of supported encryption and hash algorithms
  src/Cedar/Interop_OpenVPN.c
  src/Cedar/Interop_OpenVPN.h
  src/Mayaqua/Str.c
  src/Mayaqua/Str.h
Labels: protocol/OpenVPN

#609 another attempt to fix launchpad builds
  .travis.yml
  debian/rules
  debian/softether-vpnbridge.install
  debian/softether-vpnclient.install
  debian/softether-vpncmd.install
  debian/softether-vpnserver.install
Labels: build & release

#618 recursive git checkout for launchpad
  debian/rules
Labels: build & release

#622 add debian package builds to gitlab-ci.yml
  .gitlab-ci.yml
Labels: build & release

#620 BUILD_UNIX.md: add commands to checkout the submodule(s)
  src/BUILD_UNIX.md
Labels: build & release, documentation

#621 ignore temp cmake files, check whether cloned recursively
  .gitignore
  CMakeLists.txt
Labels: build & release

#623 launchpad builds: add "git" as a build dependency
  debian/control
Labels: build & release

#626 debian: switch packaging format from "quilt" to "native"
  debian/source/format
Labels: build & release

#629 debian: try to initialize submodules on very early stage
  debian/rules
Labels: build & release

#631 CMake: add support for Debian packaging with CPack
  .ci/check-debian-package-version.sh
  .gitlab-ci.yml
  .travis.yml
  CMakeLists.txt
  debian/README.TXT
  debian/bin/vpnbridge
  debian/bin/vpnclient
  debian/bin/vpncmd
  debian/bin/vpnserver
  debian/changelog
  debian/compat
  debian/control
  debian/dch-generate.sh
  debian/rules
  debian/softether-vpnbridge.install
  debian/softether-vpnclient.install
  debian/softether-vpncmd.install
  debian/softether-vpnserver.init
  debian/softether-vpnserver.install
  description
  src/CMakeLists.txt
Labels: build & release

#632 Cedar: fix implicit function declaration warnings
  src/Cedar/Console.c
  src/Cedar/VLanUnix.h
Labels: build & release

#633 Encrypt.c: don't use deprecated OpenSSL functions
  src/Mayaqua/Encrypt.c
Labels: build & release

#637 Change the order of commands SE manual installation docs
  src/BUILD_UNIX.md
Labels: build & release

#645 add coverity scan to travis-ci matrix
  .ci/coverity.sh
  .travis.yml
Labels: build & release

#616 CMake: change output directory from "bin" to "build"
  .gitignore
  .travis.yml
  CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpncmd/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
Labels: build & release

#646 travis-ci: small coverity fixes
  .ci/coverity.sh
  .travis.yml
Labels: build & release

#652 Mayaqua/Encrypt.c: fix invalid features.aes for mips, ppc
  src/Mayaqua/Encrypt.c
Labels: build & release

#653 GitLab: compile and install latest version of CMake
  .gitlab-ci.yml
Labels: build & release

#655 GitLab: install "wget"
  .gitlab-ci.yml
Labels: build & release

#649 Interop_OpenVPN: set "subnet" topology and remove workaround for "net30" topology on Win32
  src/Cedar/IPsec_IPC.c
  src/Cedar/IPsec_IPC.h
  src/Cedar/Interop_OpenVPN.c
  src/Cedar/Interop_OpenVPN.h
Labels: protocol/OpenVPN

#648 CMake: add support for RPM packaging with CPack
  CMakeLists.txt
  centos/README.TXT
  centos/README.md
  centos/SOURCES/fix-makefile.sh
  centos/SOURCES/init.d/vpnserver
  centos/SOURCES/linux_32bit.mak
  centos/SOURCES/linux_64bit.mak
  centos/SOURCES/scripts/vpnbridge
  centos/SOURCES/scripts/vpnclient
  centos/SOURCES/scripts/vpncmd
  centos/SOURCES/scripts/vpnserver
  centos/SPECS/softethervpn.spec
  configure
Labels: build & release

#657 gitlab-ci: refactoring
  .gitlab-ci.yml
  configure
Labels: build & release

#594 Remove SSLv3 support
  src/Cedar/AzureClient.c
  src/Cedar/CM.c
  src/Cedar/Client.c
  src/Cedar/Command.c
  src/Cedar/Connection.c
  src/Cedar/Connection.h
  src/Cedar/Protocol.c
  src/Cedar/Protocol.h
  src/Cedar/Server.c
  src/Cedar/Virtual.c
  src/Cedar/WinUi.c
  src/Cedar/WinUi.h
  src/Cedar/Wpc.c
  src/Mayaqua/Network.c
  src/Mayaqua/Network.h
  src/PenCore/PenCore.rc
  src/PenCore/resource.h
  src/bin/hamcore/strtable_cn.stb
  src/bin/hamcore/strtable_en.stb
  src/bin/hamcore/strtable_ja.stb
  src/bin/hamcore/strtable_ko.stb
  src/bin/hamcore/strtable_tw.stb
Labels: security

#664 silence several coverity "issues"
  src/Cedar/Client.c
  src/Cedar/Virtual.c
  src/Mayaqua/Network.c
  src/Mayaqua/Unix.c
Labels: cleanup

#665 src/Cedar/Client.c: remove redundant "if" statement, unused variable
  src/Cedar/Client.c
Labels: cleanup

#669 src/Mayaqua/Network.c: silence coverity on "Unchecked return value"
  src/Mayaqua/Network.c
Labels: cleanup

#670 Add TAP devices support for FreeBSD and OpenBSD
  src/CMakeLists.txt
  src/Cedar/BridgeUnix.c
  src/Cedar/Cedar.h
  src/Cedar/Server.c
  src/Cedar/VLanUnix.c
Labels: os/BSD

#675 Cedar: fix segmentation fault during local bridge creation on FreeBSD
  src/Cedar/BridgeUnix.c
Labels: os/BSD

#672 Unix.c: remove macOS-specific UnixGetTick64() implementation
  src/Mayaqua/Unix.c
Labels: os/macOS

#678 src/Mayaqua/Unix: remove unused code, improve readability of "ifdef"
  src/Mayaqua/Unix.c
Labels: cleanup

#673 Cedar: custom TAP interface name support for FreeBSD, function refactor
  src/Cedar/Cedar.h
  src/Cedar/VLanUnix.c
Labels: os/BSD

#682 src/Cedar/Session: resolve coverity "issue", remove unused functions
  src/Cedar/Session.c
  src/Cedar/Session.h
Labels: cleanup

#683 resolve several issues found by coverity
  src/Cedar/Hub.c
  src/Cedar/IPsec_EtherIP.c
  src/Cedar/Interop_OpenVPN.c
Labels: cleanup
