Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2018-07, with the labels that each got.

#577 CMake: fix pthread detection
  src/CMakeLists.txt
Labels: build & release

#579 debian: resolve "nonexistent" path in packaging
  debian/makefile.patch
  debian/rules
  debian/softether-vpnbridge.install
  debian/softether-vpnclient.install
  debian/softether-vpncmd.install
  debian/softether-vpnserver.install
Labels: build & release

#580 BUILD_UNIX.md: improve documentation as discussed in #558
  src/BUILD_UNIX.md
Labels: build & release, documentation

#438 Solaris: use DLPI style 1 attachment and check for /dev/net used by Illumos and Solaris 10+.
  src/Cedar/BridgeUnix.c
  src/Cedar/BridgeUnix.h
Labels: help wanted

#581 src: split CMakeLists.txt for each subdirectory
  src/CMakeLists.txt
  src/Cedar/CMakeLists.txt
  src/Mayaqua/CMakeLists.txt
  src/hamcorebuilder/CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpncmd/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
Labels: build & release

#582 Encrypt.c: check whether OpenSSL compression and FIPS features are available
  src/Mayaqua/Encrypt.c
Labels: build & release

#588 BUILD_WINDOWS.md: add more info regarding the software and provide download links
  src/BUILD_WINDOWS.md
Labels: documentation

#595 CMake: use find_package() and link Cedar to Ncurses
  .travis.yml
  CMakeLists.txt
  configure
  src/CMakeLists.txt
  src/Cedar/CMakeLists.txt
  src/Mayaqua/CMakeLists.txt
Labels: build & release

#584 Mayaqua: use included zlib headers only on Windows
  src/Mayaqua/Memory.c
  src/Mayaqua/win32_inc/zconf.h
  src/Mayaqua/win32_inc/zlib.h
Labels: build & release
