Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2019-07, with the labels that each got.

#947 travis-ci: add sonar-scan, update openssl, libressl
  .ci/sonarcloud.sh
  .travis.yml
Labels: build & release

#953 Deprecated OpenSSL API fixes.
  .ci/build-openssl.sh
  src/Mayaqua/Encrypt.c
  src/Mayaqua/Encrypt.h
Labels: security

#957 Add interface for easy protocol implementation
  src/Cedar/Cedar.c
  src/Cedar/Cedar.h
  src/Cedar/Cedar.vcproj
  src/Cedar/Connection.c
  src/Cedar/Proto.c
  src/Cedar/Proto.h
  src/Cedar/Proto_OpenVPN.c
  src/Cedar/Proto_OpenVPN.h
  src/Cedar/Protocol.c
  src/Mayaqua/MayaType.h
  src/Mayaqua/Network.c
  src/Mayaqua/Network.h
Labels: protocol/OpenVPN
