Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2019-10, with the labels that each got.

#1009 Move HTTP related functions to dedicated file(s) in Mayaqua
  src/Cedar/CedarType.h
  src/Cedar/Protocol.c
  src/Cedar/Protocol.h
  src/Mayaqua/HTTP.c
  src/Mayaqua/HTTP.h
  src/Mayaqua/MayaType.h
  src/Mayaqua/Mayaqua.h
  src/Mayaqua/Mayaqua.vcproj
  src/Mayaqua/Network.c
  src/Mayaqua/Network.h
Labels: refactor

#1011 Protocol.c: fix bug in ClientConnectGetSocket() causing custom HTTP header not to work
  src/Cedar/Protocol.c
Labels: bug

#1012 Mayaqua.h: include <stdarg.h> for "va_list" on Illumos
  src/Mayaqua/Mayaqua.h
Labels: build & release

#1018 Proto_OpenVPN.c: fix segmentation fault in OvsProceccRecvPacket()
  src/Cedar/Proto_OpenVPN.c
Labels: bug, protocol/OpenVPN

#1020 Proto_OpenVPN.c: improve OvsProcessData(), fix out-of-bounds access found by Coverity
  src/Cedar/Proto_OpenVPN.c
Labels: protocol/OpenVPN

#1024 Make install dir for unit files configurable
  CMakeLists.txt
  src/vpnbridge/CMakeLists.txt
  src/vpnclient/CMakeLists.txt
  src/vpnserver/CMakeLists.txt
Labels: build & release
