Repository SoftEtherVPN/SoftEtherVPN, pull requests merged in 2020-04, with the labels that each got.

#1072 Rewriting the PPP stack
  src/Cedar/CedarType.h
  src/Cedar/Proto_PPP.c
  src/Cedar/Proto_PPP.h
  src/Mayaqua/Network.c
  src/Mayaqua/Network.h
Labels: protocol/SSTP

#1093 Fix security issue: Fix the security of JSON-API
  src/Cedar/Admin.c
Labels: security

#1092 src/Cedar/Proto_OpenVPN.c: push "block-outside-dns" to clients
  src/Cedar/Proto_OpenVPN.c
Labels: os/Windows, protocol/OpenVPN, security
